- name: General | Install PHP
  action: apt pkg={{ item }} state=installed
  tags: php5
  with_items:
    - php5
    - php5-mysql
    - php-apc
    - php5-xmlrpc
    - php-soap
    - php5-gd
- name: PHP | Configuration file, php.ini
  action: template src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini
  tags: php5

- name: APC | Cache configuration file, apc.ini
  action: template src=etc-php5-conf-d-apc-ini.j2 dest=/etc/php5/conf.d/apc.ini
  tags: php5
