---
- name: General | Install required packages.
  action: apt pkg={{ item }} state=installed
  tags: common
  with_items:
    - sendmail
    - unzip
    
- name: General | Message of the day explaining server is under Ansible control.
  action: copy src=etc-update-motd-d-95-ansible dest=/etc/update-motd.d/95-ansible mode=755
  tags: common
